#version: '3.9'

services:
  api:
    image: dime/diag-terms-api:latest
    container_name: diag-terms-api
    ports:
      - "8081:8081"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      TERMS_SERVICE_URL: http://diag-terms-store:8083
      TERMS_SERVICE_MAX_RETRIES: 10
      TERMS_SERVICE_RETRY_INTERVAL_MILLIS: 60
      PORT: 8081
      WORDS_API_KEY: ${WORDS_API_KEY}
      PEXELS_API_KEY: ${PEXELS_API_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/api/health" ]
      interval: 300s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - ms-network
    volumes:
      - api-data:/var/lib/api/data

networks:
  ms-network:
    name: kafka-network
    external: true
volumes:
  api-data: